### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by jwilczek** [raralabs/pm5-emulator#14]
When trying to run the emulator after `make all`, I get  the following error:

```
./pm5-emulator : 1: Syntax error: "(" unexpected
```

**Comment by anisbhsl** [comment]
Hi @jwilczek ,
Could you please outline your device specifications, steps you tried so that I can re-produce the problem? Have you tried turning BLE service down and used root permission to run the binary?

**Comment by jwilczek** [comment]
This was entirely my mistake. The error I was seeing did not fit the root cause. After digging a little deeper I noticed the default Makefile was for a 64 bit OS and I'm on a 32. I recompiled for a 32bit os and all is working now. Thanks for the quick response!

I may reach out in the future with additional questions as I try to make use of this awesome tool!
