### ISSUE TITLE
Update readme and makefile  

### ISSUE THREAD

**Issue by anisbhsl** [raralabs/pm5-emulator#20]
Objectives: 
- Update Makefile to improve compatibility
- Make changes to the readme with cross platform build guidelines

PRs:
#19

**Comment by MoralCode** [comment]
@anisbhsl should this be closed to since the associated PR has been merged?

**Comment by anisbhsl** [comment]
@MoralCode Thank you for updating the Makefile and Readme. 
Closing this issue for now. However there is still a blocker for Apple silicon build!

**Comment by MoralCode** [comment]
wound a new issue be worth making to track that still-open item? I have a 2018 mac mini i could maybe test with if needed, but nothing apple silicon. ill see if i can ask around
