### ISSUE TITLE
make all : undefined: gatt.LnxMaxConnections

### ISSUE THREAD

**Issue by githubqt** [raralabs/pm5-emulator#21]
➜  pm5-emulator-master make test
# pm5-emulator/emulator
emulator/emulator_factory.go:26:7: undefined: gatt.LnxMaxConnections
emulator/emulator_factory.go:27:7: undefined: gatt.LnxDeviceID
emulator/emulator_factory.go:28:7: undefined: gatt.LnxSetAdvertisingParameters

**Comment by anisbhsl** [comment]
@githubqt what's your build environment?

**Comment by githubqt** [comment]
➜  pm5-emulator go version
go version go1.18.10 darwin/amd64

environment：
mac OX 13.2.1 (22D68)

**Comment by anisbhsl** [comment]
Sadly we haven't been able to compile this package with `darwin/amd64` architecture due to limitation of `gatt` package we're using. I will keep this issue open for a while to see if there're any updates in the future.

**Comment by githubqt** [comment]
Thank! I want to know the go versions of the supported mac.

**Comment by githubqt** [comment]
switch go version

`[root@ecs pm5-emulator]# sudo ./pm5-emulator
2023/08/02 10:52:56 got 0 devices
2023/08/02 10:52:56 Failed to open config, err: no supported devices available
[root@ecs pm5-emulator]# go version
go version go1.17.13 linux/amd64`

**Comment by MoralCode** [comment]
looks like this is a known issue. was able to find some additional detail at https://github.com/bettercap/bettercap/issues/74

**Comment by anisbhsl** [comment]
@MoralCode Adrian, do you have any "well-maintained" packages in mind which can be alternative to bettercap? I found this https://github.com/tinygo-org/bluetooth but this doesn't seem to have support for advertisement and others for macOS.

**Comment by MoralCode** [comment]
Fixed it. 

use [this](https://github.com/bettercap/gatt/blob/df6e615f2f67bd19ca29e20f0f0895c3ff617519/examples/option/option_darwin.go#L9C28-L11C2) set of options in place of whatever value is currently set as the default there at the bottom of `emulator/emulator_factory.go`

Long term this probably needs some kind of compile time flag to detect macos and use this value

**Comment by MoralCode** [comment]
> Adrian, do you have any "well-maintained" packages in mind which can be alternative to bettercap?

im not too familiar with the bluetooth in go space and havent really touched go since probably my last contribution to this project, so im not sure whats well maintained, but i found github.com/orca-io/gatt while looking at forks of bettercap/gatt that were newer. given that it appears (on first glance of the name) to be a company owned org, it may be the most currently maintained thing in that lineage of code

**Comment by MoralCode** [comment]
to be completely honest tho, i don't think this is an issue with the lib being un/undermaintained. It just seems like the API is different /not present for handling those three items from the error message. you can see them if you compare the darwin and linux versions of the file that i linked above with the fix.

**Comment by anisbhsl** [comment]
> It just seems like the API is different /not present for handling those three items from the error message. you can see them if you compare the darwin and linux versions of the file that i linked above with the fix.

True. I just checked with this fix in my Apple silicon. Seemed to work with 

```
var defaultServerOptions = []gatt.Option{
	gatt.MacDeviceRole(gatt.PeripheralManager),
}
```
in `emulator/emulator_factory.go`

How about we detect OS at runtime and provide server options based upon the GOOS?

**Comment by githubqt** [comment]
`
➜  pm5-emulator ./pm5-emulator
2023/08/02 14:43:05 error: connection invalid
`

**Comment by MoralCode** [comment]
hmm ok so i guess nobody (myself included) actually tested that PR completely. see #23 

> `➜ pm5-emulator ./pm5-emulator 2023/08/02 14:43:05 error: connection invalid`

I'm also seeing the same error, not super sure how to resolve this particular one. Maybe this should be put into a new issue?

**Comment by githubqt** [comment]
Yes 👌

**Comment by anisbhsl** [comment]
Saw similar error on my machine. Will try to investigate on it over this weekend.

**Comment by MoralCode** [comment]
> Saw similar error on my machine. Will try to investigate on it over this weekend.

should i open a separate issue for it since this is now closed?

**Comment by anisbhsl** [comment]
Yes please! Let's move this `connection invalid` error to new issue.
